// Code generated by protoc-gen-go.
// source: loginreply.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type LoginReply_Authorized int32

const (
	LoginReply_SUCCESSFUL LoginReply_Authorized = 0
	LoginReply_FAILED     LoginReply_Authorized = 1
)

var LoginReply_Authorized_name = map[int32]string{
	0: "SUCCESSFUL",
	1: "FAILED",
}
var LoginReply_Authorized_value = map[string]int32{
	"SUCCESSFUL": 0,
	"FAILED":     1,
}

func (x LoginReply_Authorized) Enum() *LoginReply_Authorized {
	p := new(LoginReply_Authorized)
	*p = x
	return p
}
func (x LoginReply_Authorized) String() string {
	return proto.EnumName(LoginReply_Authorized_name, int32(x))
}
func (x *LoginReply_Authorized) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LoginReply_Authorized_value, data, "LoginReply_Authorized")
	if err != nil {
		return err
	}
	*x = LoginReply_Authorized(value)
	return nil
}

type LoginReply struct {
	Authorized       *LoginReply_Authorized `protobuf:"varint,1,opt,name=authorized,enum=protos.LoginReply_Authorized" json:"authorized,omitempty"`
	SessionID        *string                `protobuf:"bytes,2,opt,name=sessionID" json:"sessionID,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}

func (m *LoginReply) GetAuthorized() LoginReply_Authorized {
	if m != nil && m.Authorized != nil {
		return *m.Authorized
	}
	return LoginReply_SUCCESSFUL
}

func (m *LoginReply) GetSessionID() string {
	if m != nil && m.SessionID != nil {
		return *m.SessionID
	}
	return ""
}

func init() {
	proto.RegisterEnum("protos.LoginReply_Authorized", LoginReply_Authorized_name, LoginReply_Authorized_value)
}
